project:
  type: website

website:
  title: ""     # Hide text title since we're using an image
  navbar:
    logo: assets/images/logo.png  # ✅ Add your logo image path here
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Team
        href: team.qmd
      - text: For Lab Members
        href: for-lab-members.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=wjO-QiMAAAAJ&hl=en
      - icon: twitter
        href: https://x.com/seun_PhD
      - icon: laptop
        href: https://entomology.osu.edu/our-people/seun-oladipupo
      - icon: envelope
        href: mailto:Oladipupo.7@osu.edu
      - icon: github
        href: https://github.com/Oladipupo-hub
  page-footer:
    left: |
      Created with [RStudio](https://www.rstudio.com) and [Quarto](https://quarto.org)  
      © Seun Oladipupo, 2025, License: [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
