
project:
  type: website

website:
  title: "The Oladipupo Lab"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Team
        href: team.qmd
      - text: Publications
        href: publications.qmd
      - text: For Lab Members
        href: for-lab-members.qmd
      - text: Contact
        href: contact.qmd
    right:
      - icon: graduation-cap
        href: https://scholar.google.com/citations?user=wjO-QiMAAAAJ&hl=en
        text: "Google Scholar"
      - icon: X
        href: https://x.com/seun_PhD
         text: "Follow us on Twitter"
      - icon: laptop
        href: https://entomology.osu.edu/our-people/seun-oladipupo
        text: "PI Page"
      - icon: envelope
        href: mailto:Oladipupo.7@osu.edu
        text: "Email Me"
      - icon: github
        href: https://github.com/Oladipupo-hub
        text: "GitHub"
format:
  html:
    theme: cosmo
    css: assets/css/styles.css
