---
title: "Join Our Lab"
format: html
---

The Oladipupo Lab is a small group of smart people all dedicated to a single thing – creating sustainable tools to address urban insect problems. We want to make products. Products that improve the quality of human life. We prioritize simplicity because simplicity is key. Importantly, simple is fast! Whether you are an undergraduate, prospective graduate student, postdoc or collaborator, if our research resonates with you, we would love to hear from you.


## Interested in Joining?

If you’re interested in joining our team, please email **Seun** with:

- A short CV
- A brief paragraph on why our research excites you
- (For graduate applicants) The degree and program you’re considering

## Important for Prospective Graduate Students

The **Department of Entomology** and **Environmental Science** graduate programs admit students directly into research labs (without rotations). Admission is contingent on finding a faculty advisor who can support and mentor you throughout your degree. Because of this, it is essential to reach out and start a conversation with us **before** submitting an application.

For those hoping to start in **Fall**, applications should be completed by **December 1** of the previous year.

If you have any questions about the application process or how your interests might align with our work, please don’t hesitate to contact **Seun**.

Looking forward to hearing from you,  
Seun






