
---
title: "Publications [Google Scholar ](https://scholar.google.com/citations?user=wjO-QiMAAAAJ&hl=en)"
format:
  html:
    css: assets/css/styles.css
---


## Preprints

<span class="pub-number">18.</span> Oswalt, K., **Oladipupo, S.O.**, Mendez, L., Gillespie, J.J., Beckmann, J.F., 2025. Origin of cin: lateral transfer of cytoplasmic incompatibility nuclease operon to *Orientia tsutsugamushi*

## 2025

<span class="pub-number">17.</span> **Oladipupo, S.O.**, Hochstrasser, M., 2025. Deubiquitylases and nucleases in bacterial symbiont-induced cytoplasmic incompatibility. _Biochem. Soc. Transac._

<span class="pub-number">16.</span> Senanayaka Mudiyanselage, P., Lindsey, L., **Oladipupo, S.O.**, 2025. Does growing latitude influence soybean seed critical amino acid content? A meta-analysis. _Agric. Environ. Lett._ 10, e70033

## 2023

<span class="pub-number">15.</span> **Oladipupo, S.O.**, Laidoudi, Y., Beckmann, J.F., Hu, X.P., Appel, A.G., 2023. The prevalence of *Wolbachia* in multiple cockroach species and its implication for urban insect management. _J. Econ. Entomol._ xx, 1–10. **Featured in** *[Entomology Today](https://entomologytoday.org/2023/06/15/wolbachia-cockroaches-new-paradigm-urban-pest-management/)*

<span class="pub-number">14.</span> **Oladipupo, S.O.**, <sup>#</sup>Carroll, J.D., Beckmann, J.F., 2023. Convergent _Aedes_ and _Drosophila_ CidB interactomes suggest cytoplasmic incompatibility targets are conserved. _Insect Biochem. Mol. Bio._ 155, 1–8

## 2022

<span class="pub-number">13.</span> **Oladipupo, S.O.**, Hu, X.P., Appel, A.G., 2022. Essential oils in urban insect management – a review. _J. Econ. Entomol._ 115, 1375–1408. **Featured in** *[Entomology Today](https://entomologytoday.org/2022/07/14/essential-oils-untapped-resource-managing-urban-insect-pests/)*

<span class="pub-number">12.</span> Eckert, J.P., **Oladipupo, S.O.**, et al., 2022. Which trap is best? Alternatives to human landing catches for malaria vector surveillance: a meta-analysis. _Malar. J._ 21, 378

<span class="pub-number">11.</span> **Oladipupo, S.O.**, Wilson, A.E., Hu, X.P., Appel, A.G., 2022. Why do insects close their spiracles? A meta-analytic evaluation of the hypotheses of discontinuous gas exchange in insects. _Insects_ 13, 117–121

<span class="pub-number">10.</span> DadeMatthews, O., Agostinelli, P., Neal, F., **Oladipupo, S.O.**, et al., 2022. Systematic review and meta-analyses on the effects of whole-body vibration on bone health. _Complimentary Ther. Med._ 65, 1–15

## 2021 and Earlier

<span class="pub-number">9.</span> Beckmann, J.F., Dormitorio, T.V., **Oladipupo, S.O.**, et al., 2021. *Heterakis gallinarum* and *Histomonas meleagridis* DNA persists in chicken houses years after depopulation. _Vet. Parasitol._ 109536

<span class="pub-number">8.</span> Gbaye, O.A., **Oladipupo, S.O.**, Oyeniyi, E.A., <sup>#</sup>Oladipupo, T.H., 2021. Impact of sublethal doses of *Piper guineense* on *Callosobruchus maculatus* reared on cowpea varieties. _J. Asia Pac. Entomol._ 24, 529–535

<span class="pub-number">7.</span> **Oladipupo, S.O.**, Hu, X.P., Appel, A.G., 2020. Essential oil components in polymer gel modify reproduction of *Blattella germanica*. _J. Econ. Entomol._ 113, 2436–2447

<span class="pub-number">6.</span> **Oladipupo, S.O.**, Hu, X.P., Appel, A.G., 2020. Topical toxicity of essential oil components against the German cockroach. _J. Econ. Entomol._ 113, 896–904

<span class="pub-number">5.</span> **Oladipupo, S.O.**, Callaghan A., Holloway, G.J., Gbaye, O.A., 2019. Variation in susceptibility of *Anopheles gambiae* to botanicals across Nigeria. _PLoS ONE_ 14, e0210440

<span class="pub-number">4.</span> Ajayi, O.E., **Oladipupo, S.O.**, <sup>#</sup>Ajisafe, O., 2019. Influence of processing and substrate variety on survival of *Tribolium confusum*. _Arch. Phyto. Plant Prot._ 52, 356–370

<span class="pub-number">3.</span> **Oladipupo, S.O.**, Adedire, C.O., Gbaye, O.A., 2018. Fecundity and survival of *Carpophilus hemipterus* on alternative hosts. _Braz. J. Biol. Sci._ 5, 115–123

<span class="pub-number">2.</span> Ajayi, O.E., **Oladipupo, S.O.**, <sup>#</sup>Ojo, T.B., 2018. Fumigant toxicity of clove and lemongrass oils on *Tribolium castaneum*. _J. J. Bio. Sci._ 11, 571–575

<span class="pub-number">1.</span> Ajayi, O.E., **Oladipupo, S.O.**, Jegede, O.J., 2018. Influence of plant extracts on activity of *Callosobruchus chinensis*. _Med. Plant Res._ 8, 60–73

_<sup>#</sup> indicates publication by a student mentee_

---

### Ph.D Thesis
- **Oladipupo, S.O.**, 2022. Toxicity and physiological effects of essential oil components against the German Cockroach, *Blattella germanica* (L.)

---
